language: c++

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      service: docker
    - os: linux
      compiler: clang
      sudo: required
      service: docker
    - os: osx
      compiler: gcc
      service: docker
    - os: osx
      compiler: clang
      service: docker

addons:
  apt:
    sources:
    - george-edison55-precise-backports 
    packages:
    - cmake
    - cmake-data



before_install:
- docker build -t conan_gbenchmark .

script:
- docker run conan_gbenchmark /bin/bash -c "cd /test; ./runTest.py"
